apiVersion: apps/v1
kind: Deployment
metadata:
  name: telnet-server
  namespace: devops-admin
  labels:
    app: telnet-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telnet-server
  template:
    metadata:
      labels:
        app: telnet-server
    spec:
      securityContext:
        runAsUser: 1001
        fsGroup: 1001
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: telnet-server
        # ✅ Use a small Alpine image that includes telnetd and xinetd
        image: alpine:3.19
        command: ["sh", "-c"]
        args:
        - |
          apk add --no-cache busybox-extras xinetd && \
          mkdir -p /etc/xinetd.d && \
          echo "service telnet
          {
              disable         = no
              flags           = REUSE
              socket_type     = stream
              wait            = no
              user            = nobody
              server          = /usr/sbin/in.telnetd
              log_on_failure  += USERID
              port            = 2323
          }" > /etc/xinetd.d/telnet && \
          echo "defaults
          {
              log_type        = SYSLOG authpriv
              log_on_failure  = HOST
              log_on_success  = PID HOST EXIT DURATION
          }
          includedir /etc/xinetd.d" > /etc/xinetd.conf && \
          echo "✅ Telnet server starting on port 2323..." && \
          xinetd -stayalive -dontfork
        ports:
        - containerPort: 2323
          name: telnet
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 1001
          runAsGroup: 1001
          capabilities:
            drop: ["ALL"]
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
        livenessProbe:
          tcpSocket:
            port: 2323
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          tcpSocket:
            port: 2323
          initialDelaySeconds: 10
          periodSeconds: 15
        startupProbe:
          tcpSocket:
            port: 2323
          initialDelaySeconds: 15
          periodSeconds: 10
          failureThreshold: 30
  strategy:
    type: Recreate
---
apiVersion: v1
kind: Service
metadata:
  name: telnet-service
  namespace: devops-admin
spec:
  selector:
    app: telnet-server
  ports:
  - name: telnet
    protocol: TCP
    port: 2323
    targetPort: 2323
  type: ClusterIP
